---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: piaware
  namespace: home-automation
spec:
  interval: 5m
  chart:
    spec:
      chart: flightradar24
      version: 1
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m

  values:
    image:
      # -- image repository
      repository: mikenye/fr24feed
      # -- image tag
      tag: "1.0.29-8"
      # -- image pull policy
      pullPolicy: IfNotPresent

    # -- environment variables. See [application docs](https://flightaware.com/adsb/piaware/advanced_configuration) for more details.
    # @default -- See below
    env:
      # -- Set the container timezone
      TZ: "${TIMEZONE}"
      FEEDER_LAT: "${LATITUDE}"
      FEEDER_LONG: "${LONGITUDE}"
      FEEDER_ALT_FT: 305
      FR24_EMAIL:  "${EMAIL_POSTMASTER}"