---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: tv-head-end
  namespace: media
spec:
  interval: 5m
  chart:
    spec:
      chart: tvheadend
      version: 5.3.1
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      # -- image repository
      repository: ghcr.io/linuxserver/tvheadend
      # -- image tag
      tag: version-eb59284b
      # -- image pull policy
      pullPolicy: IfNotPresent

    # -- environment variables. See [image docs](https://docs.linuxserver.io/images/docker-tvheadend#environment-variables-e) for more details.
    # @default -- See below
    env:
      # -- Set the container timezone
      TZ: "${TIMEZONE}"
      # -- Specify the user ID the application will run as
      PUID: "1001"
      # -- Specify the group ID the application will run as
      PGID: "1001"

    # -- Configures service settings for the chart.
    # @default -- See values.yaml
    service:
      main:
        ports:
          http:
            enabled: true
            port: 9981
          htsp:
            enabled: true
            protocol: TCP
            port: 9982

    ingress:
      main:
        enabled: true
        primary: true
        #        ingressClassName: "traefik"
        annotations:
          kubernetes.io/ingress.class: "traefik"
          cert-manager.io/cluster-issuer: letsencrypt
        hosts:
          - host: &host "tvheadend.${INGRESS_DOMAIN}"
            paths:
              - path: /
        tls:
          - secretName: tls.tvheadend
            hosts:
              - *host

    # -- Configure persistence settings for the chart under this key.
    # @default -- See values.yaml
    persistence:
      config:
        enabled: false
        mountPath: /config
      recordings:
        enabled: false
        mountPath: /recordings
    
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
                - key: feature.node.kubernetes.io/wintV-quadhd
                  operator: In
                  values:
                    - "true"