---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: media-tvheadend-config-config-pv-volume
spec:
  storageClassName: ""
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/srv/docker/k3s/tvheadend/"
  persistentVolumeReclaimPolicy: Retain
