---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media-tvheadend-config-pv-claim
  namespace: media
spec:
  accessModes:
    - ReadWriteOnce

  resources:
    requests:
      storage: 1Gi

  storageClassName: ""
  volumeName: media-tvheadend-config-pv-volume

  