---
creation_rules:
  - path_regex: (global|clusters)/.*\.sops\.ya?ml
    encrypted_regex: "((?i)(pass|secret($|[^N])|key|token|^data$|^stringData))"
    # Personal, Flux
    age: age1xsknylevdyrdq858yj57hc0caf477gqyqny8eyl7ekama7ffsf6qrrg28v
