---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: aircraft-namespace
  namespace: flux-system
spec:
  interval: 5m
  path: "./clusters/k8s-home-lab/manifests/aircraft"
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: home-ops
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: aircraft-readsb-protobuf
  namespace: flux-system
spec:
  dependsOn:
    - name: aircraft-namespace
  interval: 5m
  path: "./clusters/k8s-home-lab/manifests/aircraft/readsb-protobuf"
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: home-ops