---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: home-automation-namespace
  namespace: flux-system
spec:
  interval: 5m
  path: "./clusters/k8s-home-lab/manifests/home-automation"
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: home-ops
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: home-automation-mosquitto
  namespace: flux-system
spec:
  # dependsOn:
  #   - name: home-automation-namespace
  interval: 5m
  path: "./clusters/k8s-home-lab/manifests/home-automation/mosquitto"
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: home-ops
# ---
# apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
# kind: Kustomization
# metadata:
#   name: home-automation-zigbee2mqtt
#   namespace: flux-system
# spec:
#   # dependsOn:
#   #   - name: home-automation-namespace
#   #   - name: home-automation-mosquitto
#   interval: 5m
#   path: "./clusters/k8s-home-lab/manifests/home-automation/zigbee2mqtt"
#   prune: true
#   wait: true
#   sourceRef:
#     kind: GitRepository
#     name: home-ops
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: home-automation-home-assistant
  namespace: flux-system
spec:
  # dependsOn:
  #   - name: home-automation-namespace
  #   - name: home-automation-mosquitto
  #   - name: home-automation-home-assistant-database
  interval: 5m
  path: "./clusters/k8s-home-lab/manifests/home-automation/home-assistant"
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: home-ops