---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  #- ./cert-manager.yaml
  - ./system.yaml
 # - ./vpn.yaml
  - ./media.yaml
 # - ./downloads.yaml
  - ./home-automation.yaml
  - ./aircraft.yaml
  - ./monitoring.yaml