---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: media-namespace
  namespace: flux-system
spec:
  interval: 5m
  path: "./clusters/k8s-home-lab/manifests/media"
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: home-ops
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: media-plex
  namespace: flux-system
spec:
  dependsOn:
    - name: media-namespace
  interval: 5m
  path: "./clusters/k8s-home-lab/manifests/media/plex"
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: home-ops