---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: monitoring-namespace
  namespace: flux-system
spec:
  interval: 5m
  path: "./clusters/k8s-home-lab/manifests/monitoring"
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: home-ops
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: monitoring-prometheus
  namespace: flux-system
spec:
  dependsOn:
    - name: monitoring-namespace
  interval: 5m
  path: "./clusters/k8s-home-lab/manifests/monitoring/prometheus"
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: home-ops
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: monitoring-influxdb
  namespace: flux-system
spec:
  dependsOn:
    - name: monitoring-namespace
  interval: 5m
  path: "./clusters/k8s-home-lab/manifests/monitoring/influxdb"
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: home-ops
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: monitoring-grafana
  namespace: flux-system
spec:
  dependsOn:
    - name: monitoring-namespace
  interval: 5m
  path: "./clusters/k8s-home-lab/manifests/monitoring/grafana"
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: home-ops
---