--- 
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata: 
  name: system-node-feature-discovery
  namespace: flux-system
spec: 
  interval: 5m
  path: ./clusters/k8s-home-lab/manifests/system/node-feature-discovery
  prune: true
  sourceRef: 
    kind: GitRepository
    name: home-ops
  wait: true
