---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: system-namespace
  namespace: flux-system
spec:
  interval: 5m
  path: "./clusters/k8s-home-lab/manifests/system"
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: home-ops
---
# apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
# kind: Kustomization
# metadata:
#   name: system-intel-gpu-plugin
#   namespace: flux-system
# spec:
#   dependsOn:
#     - name: system-namespace
#   interval: 5m
#   path: "./clusters/k8s-home-lab/manifests/system/intel-gpu-plugin"
#   prune: true
#   wait: true
#   sourceRef:
#     kind: GitRepository
#     name: home-ops
# ---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: system-reloader
  namespace: flux-system
spec:
  dependsOn:
    - name: system-namespace
  interval: 5m
  path: ""./clusters/k8s-home-lab/manifests/system/reloader"
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: home-ops
# ---
# apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
# kind: Kustomization
# metadata:
#   name: system-node-feature-discovery
#   namespace: flux-system
# spec:
#   dependsOn:
#     - name: system-namespace
#   interval: 5m
#   path: "./clusters/k8s-home-lab/manifests/system/node-feature-discovery"
#   prune: true
#   wait: true
#   sourceRef:
#     kind: GitRepository
#     name: home-ops