---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: mosquitto
  namespace: home-automation
spec:
  interval: 5m
  chart:
    spec:
      chart: mosquitto
      version: 4.3.1
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m

  values:
    image:
      repository: eclipse-mosquitto
      tag: 2.0.14

    podAnnotations:
      secret.reloader.stakater.com/reload: mosquitto-config

    service:
      main:
        ports:
          http:
            enabled: false
          mqtt:
            externalTrafficPolicy: Local
            type: LoadBalancer
            enabled: true
            port: 1883

    auth:
      enabled: false

    persistence:
      data:
        enabled: true
        existingClaim: mosquitto-data
      configinc:
        enabled: false
        type: custom
        volumeSpec:
          secret:
            secretName: mosquitto-config

      CA_CERT:
        enabled: false
        type: custom
        volumeSpec:
          secret:
            secretName: CA_CERT
            items:
              path: /mosquitto/config/certs/ca.crt

      SERVER_CERT:
        enabled: false
        type: custom
        volumeSpec:
          secret:
            secretName: SERVER_CERT
            items:
              path: /mosquitto/config/certs/server.crt

      SERVER_KEY:
        enabled: false
        type: custom
        volumeSpec:
          secret:
            secretName: SERVER_KEY
            items:
              path: /mosquitto/config/certs/server.key

    resources:
      requests:
        cpu: 15m
        memory: 64M
      limits:
        memory: 64M