apiVersion: v1
kind: PersistentVolume
metadata:
  name: downloads-pv-volume
spec:
  storageClassName: ""
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/srv/docker/downloads"
  persistentVolumeReclaimPolicy: Retain