apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: downloads-pv-claim
  namespace: downloads
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi