apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: downloads-pv-claim
  namespace: downloads
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 8Gi
  volumeName: downloads-pv-volume