---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: downloads-radarr-config-pv-claim
  namespace: downloads
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  volumeName: downloads-radarr-config-pv-volume
