---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nzbget
  namespace: downloads
spec:
  interval: 5m
  chart:
    spec:
      chart: nzbget
      version: 12.2.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m

  values:
    image:
      repository: ghcr.io/k8s-at-home/nzbget-testing
      tag: "v21.1"

    podSecurityContext:
      supplementalGroups:
        - 65539

    env:
      TZ: "${TIMEZONE}"

    persistence:
      config:
        enabled: true
        existingClaim: nzbget-config-pvc
      scripts:
        enabled: false
        type: configMap
        name: nzbget-scripts
        mountPath: /scripts
        readOnly: true
        defaultMode: 0555
      media:
        enabled: false
        type: custom
        volumeSpec:
          nfs:
            server: "${NAS_ADDRESS}"
            path: /volume1/Media
        mountPath: /data/nas-media
      downloads:
        enabled: false
        mountPath: /downloads

    podAnnotations:
      setGateway: "true"

    ingress:
      main:
        enabled: true
        primary: true
        #        ingressClassName: "traefik"
        annotations:
          kubernetes.io/ingress.class: "traefik"
          cert-manager.io/cluster-issuer: letsencrypt
        hosts:
          - host: &host "nzbget.${INGRESS_DOMAIN}"
            paths:
              - path: /
        tls:
          - secretName: tls.nzbget
            hosts:
              - *host

    resources:
      requests:
        memory: "128M"
      limits:
        memory: "2000Mi"
