---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: readarr
  namespace: downloads
spec:
  interval: 5m
  chart:
    spec:
      chart: readarr
      version: 6.2.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: ghcr.io/k8s-at-home/readarr
      tag: v0.1.1.1306

    podSecurityContext:
      supplementalGroups:
        - 65539

    env:
      TZ: "Europe/London"

    persistence:
      config:
        enabled: true
        existingClaim: readarr-config-pvc
      media:
        enabled: false
        type: custom
        volumeSpec:
          nfs:
            server: "${NAS_ADDRESS}"
            path: /volume1/Media
        mountPath: /data/nas-media

    ingress:
      main:
        enabled: true
        ingressClassName: "traefik"
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt
          kubernetes.io/ingress.class: "traefik"
        hosts:
          - host: "readarr.peterduckett.me"
            paths:
              - path: /
        tls:
          - secretName: tls.readarr
            hosts:
              - readarr.peterduckett.me

    resources:
      requests:
        cpu: "0.04"
        memory: "256M"
      limits:
        memory: "512M"