---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: prometheus
  namespace: monitoring
spec:
  interval: 5m
  chart:
    spec:
      chart: prometheus-community/prometheus
      version: 2.36.2
      sourceRef:
        kind: HelmRepository
        name: prometheus-community-charts
        namespace: flux-system
      interval: 5m
    values:
    image:
    #   repository: ghcr.io/k8s-at-home/adguard-home
    #   tag: v0.106.3
      pullPolicy: IfNotPresent
        
  