---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
  namespace: monitoring
spec:
  interval: 15m
  maxHistory: 2
  timeout: 20m
  chart:
    spec:
      chart: kube-prometheus-stack
      version: 45.1.0
      sourceRef:
        kind: HelmRepository
        name: prometheus-community-charts
        namespace: flux-system
      interval: 15m

  values:
    ingress:
      enabled: true
      hosts:
        - host: &host "prometheus.${INGRESS_DOMAIN}"
          paths:
            - path: /
      tls:
        - secretName: tls.prometheus
          hosts:
            - *host
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt
        kubernetes.io/ingress.class: "traefik"
