---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: readsb-protobuf
  namespace: aircraft
spec:
  interval: 5m
  chart:
    spec:
      chart: test
      version: 0.1.0
      sourceRef:
        kind: HelmRepository
        name: peterduckett-charts
        namespace: flux-system
      interval: 5m

  values:
    image:
      # -- image repository
      repository: mikenye/readsb-protobuf
      # -- image tag
      tag: "v4.0.3"
      # -- image pull policy
      pullPolicy: IfNotPresent

    # -- environment variables. See [application docs](https://flightaware.com/adsb/piaware/advanced_configuration) for more details.
    # @default -- See below
    env:
      # -- Set the container timezone
      TZ: "${TIMEZONE}"
      READSB_DCFILTER: true
      READSB_DEVICE_TYPE: rtlsdr
      READSB_FIX: true
      READSB_GAIN: autogain
      READSB_LAT: "${LATITUDE}"
      READSB_LON: "${LONGITUDE}"
      READSB_MODEAC: true
      READSB_RX_LOCATION_ACCURACY: 2
      READSB_STATS_RANGE: true
      READSB_NET_ENABLE: true