---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: flightradar24
  namespace: aircraft
spec:
  interval: 5m
  chart:
    spec:
      chart: flightradar24
      version: 0.1.0
      sourceRef:
        kind: HelmRepository
        name: peterduckett-charts
        namespace: flux-system
      interval: 5m

  values:
    image:
      # -- image repository
      repository: mikenye/fr24feed
      # -- image tag
      tag: "1.0.29-8"
      # -- image pull policy
      pullPolicy: IfNotPresent

      #command: ["sh", "-c", "/scripts/signup.sh"]

    # initContainers:
    #   signup:
    #     image: mikenye/fr24feed:1.0.29-8
    #     command: ["sh", "-c", "/scripts/signup.sh"]
    #     env:
    #       # -- Set the container timezone
    #       - name: TZ
    #         value: "Europe/London"
    #       - name: FEEDER_LAT
    #         value: "52.646138412635"
    #       - name: FEEDER_LONG
    #         value: "-1.19837698783953"
    #       - name: FEEDER_ALT_FT
    #         value: "305.118"
    #       - name: FR24_EMAIL
    #         value: "peter.james.duckett@googlemail.com"

    # -- Configures service settings for the chart.
    # @default -- See values.yaml
    service:
      main:
        ports:
          http:
            port: 8754
          beastoutput:
            enabled: true
            port: 30105
            protocol: TCP

    ingress:
      # -- Enable and configure ingress settings for the chart under this key.
      # @default -- See values.yaml
      main:
        enabled: false

    # -- environment variables. See [application docs](https://flightaware.com/adsb/piaware/advanced_configuration) for more details.
    # @default -- See below
    env:
      # -- Set the container timezone
      TZ: "${TIMEZONE}"
      FEEDER_LAT: "${LATITUDE}"
      FEEDER_LONG: "${LONGITUDE}"
      FEEDER_ALT_FT: "{ALTITUDE_FT}"
      BEASTHOST: readsb-protobuf-test
      BEASTPORT: 30005
      FR24_EMAIL: "${EMAIL_POSTMASTER}"
      FR24KEY: 9793b4ce1c5cc412
      MLAT: true
