---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: home-automation-home-assistant-config-pv-claim
  namespace: home-automation
spec:
  accessModes:
    - ReadWriteOnce

  resources:
    requests:
      storage: 1Gi

  storageClassName: ""
  volumeName: home-automation-home-assistant-config-pv-volume

  