---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: intel-gpu-plugin
  namespace: system
spec:
  interval: 5m
  chart:
    spec:
      chart: intel-device-plugins-gpu
      version: 0.25.1
      sourceRef:
        kind: HelmRepository
        name: intel-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      #repository: ghcr.io/k8s-at-home/intel-gpu-plugin
      #tag: v0.22.0
      pullPolicy: IfNotPresent

    args:
      - -shared-dev-num
      - "2"

    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
                - key: feature.node.kubernetes.io/custom-intel-gpu
                  operator: In
                  values:
                    - "true"