---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: mlathub
  namespace: aircraft
spec:
  interval: 5m
  chart:
    spec:
      chart: test
      version: 0.1.0
      sourceRef:
        kind: HelmRepository
        name: peterduckett-charts
        namespace: flux-system
      interval: 5m

  values:
    image:
      # -- image repository
      repository: mikenye/readsb-protobuf
      # -- image tag
      tag: "v4.0.3"
      # -- image pull policy
      pullPolicy: IfNotPresent

    # -- environment variables. See [application docs](https://flightaware.com/adsb/piaware/advanced_configuration) for more details.
    # @default -- See below
    env:
      # -- Set the container timezone
      TZ: "${TIMEZONE}"
      DISABLE_PERFORMANCE_GRAPHS: true
      DISABLE_WEBAPP: true
      READSB_NET_ENABLE: true
      READSB_NET_ONLY: true
      READSB_FORWARD_MLAT: true
      READSB_NET_CONNECTOR: piaware,30105,beast_in;flightradar24,30003,sbs_out;radarbox,30105,beast_in;
      READSB_NET_BEAST_OUTPUT_PORT: 30105

    # -- Configures service settings for the chart.
    # @default -- See values.yaml
    service:
      main:
        ports:
          http:
            enabled: false
          beastoutput:
            enabled: true
            port: 30105
            protocol: TCP

    ingress:
      # -- Enable and configure ingress settings for the chart under this key.
      # @default -- See values.yaml
      main:
        enabled: false
