---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: aircraft-autograin-pv-volume
spec:
  storageClassName: ""
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/srv/docker/k3s/readsb/autograin/"
  persistentVolumeReclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: aircraft-collectd-pv-volume
spec:
  storageClassName: ""
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/srv/docker/k3s/readsb/collectd/"
  persistentVolumeReclaimPolicy: Retain
