---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: aircraft-autograin-pv-claim
  namespace: aircraft
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  volumeName: aircraft-autograin-pv-volume
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: aircraft-collectd-pv-claim
  namespace: aircraft
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  volumeName: aircraft-collectd-pv-volume