---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: bazarr
  namespace: downloads
spec:
  interval: 5m
  chart:
    spec:
      chart: bazarr
      version: 11.0.43
      sourceRef:
        kind: HelmRepository
        name: true-charts
        namespace: flux-system
      interval: 5m
  values:

    podAnnotations:
      setGateway: "true"

    env:
      TZ: "${TIMEZONE}"

    persistence:
      config:
        enabled: true
        existingClaim: downloads-bazarr-config-pv-claim
      media:
        enabled: false
        type: custom
        volumeSpec:
          nfs:
            server: "${NAS_ADDRESS}"
            path: /volume1/Media
        mountPath: /data/nas-media

    ingress:
      main:
        enabled: true
        # ingressClassName: "traefik"
        annotations:
          kubernetes.io/ingress.class: "traefik"
          cert-manager.io/cluster-issuer: letsencrypt
        hosts:
          - host: &host "bazarr.${INGRESS_DOMAIN}"
            paths:
              - path: /
        tls:
          - secretName: tls.bazarr
            hosts:
              - *host

    resources:
      requests:
        cpu: "0.04"
        memory: "256M"
      limits:
        memory: "512M"
