---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: database-mariadb-galera-pv-volume
  namespace: database
spec:
  storageClassName: ""
  capacity:
    storage: 40Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/srv/docker/k3s/mariadbgalera/"
