---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: database-mariadb-galera-pvc-claim
  namespace: database
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 40Gi
  storageClassName: ""
  volumeName: database-mariadb-galera-pv-volume

  