---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: qbittorrent
  namespace: downloads
spec:
  interval: 5m
  chart:
    spec:
      chart: qbittorrent
      version: 13.2.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: ghcr.io/k8s-at-home/qbittorrent
      tag: v4.4.2
      pullPolicy: Always

    hostname: qbittorrent

    podAnnotations:
      setGateway: "true"

    podSecurityContext:
      supplementalGroups:
        - 65539

    settings:
      automaticPortSetup: false

    env:
      TZ: "${TIMEZONE}"
      UMASK: "022"

    persistence:
      config:
        enabled: true
        existingClaim: downloads-qbittorrent-config-pv-claim
      media:
        enabled: false
        type: custom
        volumeSpec:
          nfs:
            server: "${NAS_ADDRESS}"
            path: /volume1/Media
        mountPath: /data/nas-media

    ingress:
      main:
        enabled: true
        ingressClassName: "traefik"
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt
          kubernetes.io/ingress.class: "traefik"
        hosts:
          - host: &host "qbittorrent.${INGRESS_DOMAIN}"
            paths:
              - path: /
        tls:
          - secretName: tls.qbittorrent
            hosts:
              - *host

    resources:
      requests:
        cpu: "0.3"
        memory: "1000Mi"
      limits:
        memory: "4000Mi"