---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: downloads-qbittorrent-config-pv-claim
  namespace: downloads
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
    volumeName: downloads-qbittorrent-config-pv-volume