---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: prowlarr
  namespace: downloads
spec:
  interval: 5m
  chart:
    spec:
      chart: prowlarr
      version: 4.2.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: ghcr.io/k8s-at-home/prowlarr
      tag: v0.3.0.1679
      pullPolicy: IfNotPresent

    hostname: prowlarr

    podAnnotations:
      setGateway: "true"

    env:
      TZ: "Europe/London"

    persistence:
      config:
        enabled: true
        existingClaim: prowlarr-config-pvc
      shared:
        enabled: true
        type: emptyDir
        mountPath: /shared


    ingress:
      main:
        enabled: true
        ingressClassName: "traefik"
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt
        hosts:
          - host: "prowlarr.peterduckett.me"
            paths:
              - path: /
        tls:
          - secretName: tls.prowlarr
            hosts:
              - prowlarr.peterduckett.me

    resources:
      requests:
        memory: "256M"
      limits:
        memory: "384M"