---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: lidarr
  namespace: downloads
spec:
  interval: 5m
  chart:
    spec:
      chart: lidarr
      version: 14.0.1
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: ghcr.io/k8s-at-home/lidarr
      tag: v1.0.0.2255

    podSecurityContext:
      supplementalGroups:
        - 65539

    env:
      TZ: "${TIMEZONE}"

    persistence:
      config:
        enabled: true
        existingClaim: lidarr-config-pvc
      media:
        enabled: false
        type: custom
        volumeSpec:
          nfs:
            server: "${NAS_ADDRESS}"
            path: /volume1/Media
        mountPath: /data/nas-media

    ingress:
      main:
        enabled: true
        ingressClassName: "traefik"
        annotations:
          kubernetes.io/ingress.class: "traefik"
          cert-manager.io/cluster-issuer: letsencrypt-production
        hosts:
          - host: &host "lidarr.${INGRESS_DOMAIN}"
            paths:
              - path: /
        tls:
          - secretName: tls.lidarr
            hosts:
              - *host

    resources:
      requests:
        cpu: "0.04"
        memory: "256M"
      limits:
        memory: "512M"