---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: grafana
  namespace: monitoring
spec:
  interval: 5m
  chart:
    spec:
      chart: grafana
      version: 6.50.6
      sourceRef:
        kind: HelmRepository
        name: grafana-charts
        namespace: flux-system
      interval: 5m
  timeout: 20m

  values:
    image:
      tag: 9.3.6
      pullPolicy: IfNotPresent

    ingress:
      enabled: true
 #     hostname: "grafana.peterduckett.me"
      annotations:
          cert-manager.io/cluster-issuer: letsencrypt
          kubernetes.io/ingress.class: "traefik"   
      hosts: 
        - &host "grafana.${INGRESS_DOMAIN}"
   
      tls:
        - secretName: tls.grafana
          hosts:
            - *host

    initChownData:
      enabled: false

    sidecar:
      dashboards:
        enabled: true
        searchNamespace: ALL
      datasources:
        enabled: true
        searchNamespace: ALL

    serviceMonitor:
      enabled: true

    persistence:
      enabled: true
      existingClaim: monitoring-grafana-pvc-claim

    podAnnotations:
      configmap.reloader.stakater.com/reload: "grafana"