---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: monitoring-grafana-pv-volume
  namespace: monitoring
spec:
  storageClassName: ""
  capacity:
    storage: 40Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/srv/docker/k3s/home-assistant/"  
