---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: monitoring-grafana-pvc-claim
  namespace: monitoring
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: ""
  volumeName: monitoring-grafana-pv-volume

  