---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: adguard-home
  namespace: system
spec:
  interval: 5m
  chart:
    spec:
      chart: adguard-home
      version: 5.3.1
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: ghcr.io/k8s-at-home/adguard-home
      tag: v0.106.3
      pullPolicy: IfNotPresent
        
    env:
      TZ: "${TIMEZONE}"

    args:
    - "--config"
    - "/opt/adguardhome/conf/AdGuardHome.yaml"
    - "--work-dir"
    - "/opt/adguardhome/work"
    - "--no-check-update"

  service:
    main:
      primary: true
      ports:
        http:
          port: 3000
    dns-tcp:
      enabled: true
      type: NodePort
      ports:
        dns-tcp:
          enabled: true
          port: 53
          protocol: TCP
          targetPort: 53
      externalTrafficPolicy: Local
    dns-udp:
      enabled: true
      type: NodePort
      ports:
        dns-udp:
          enabled: true
          port: 53
          protocol: UDP
          targetPort: 53
      externalTrafficPolicy: Local
  
  persistence:
    config:
      enabled: true
      existingClaim: adguard-home-config-pvc
    data:
      enabled: false
      mountPath: /opt/adguardhome/work
