---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: piaware
  namespace: aircraft
spec:
  interval: 5m
  chart:
    spec:
      chart: piaware
      version: 9.0.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m

  values:
    image:
      # -- image repository
      repository: mikenye/piaware
      # -- image tag
      tag: "v7.2"
      # -- image pull policy
      pullPolicy: IfNotPresent

    # -- environment variables. See [application docs](https://flightaware.com/adsb/piaware/advanced_configuration) for more details.
    # @default -- See below
    env:
      # -- Set the container timezone
      TZ: "${TIMEZONE}"
      LAT: "${LATITUDE}"
      LONG: "${LONGITUDE}"
      receiver-type: "relay"
      BEASTHOST: 	readsb-protobuf-test
      BEASTPORT: 30005
      #mlat-results-format: "beast,connect,localhost:30104"
      FEEDER_ID: "b30e104e-d3c1-48fe-b9f4-f80388cd70c6"

    # -- Configures service settings for the chart.
    # @default -- See values.yaml
    service:
      main:
        ports:
          http:
            port: 8080
          beastoutput:
            enabled: true
            port: 30105
            protocol: TCP

    ingress:
      # -- Enable and configure ingress settings for the chart under this key.
      # @default -- See values.yaml
      main:
        enabled: false

    securityContext:
      # -- (bool) Privileged securityContext may be required if USB device is accessed directly through the host machine
      privileged: true

    # -- Configure persistence settings for the chart under this key.
    # @default -- See values.yaml
    persistence:
      # -- Configure a hostPathMount to mount a USB device in the container.
      # @default -- See values.yaml
      usb:
        enabled: false
        type: hostPath
        hostPath: /dev/bus/usb/001/004

    # -- Affinity constraint rules to place the Pod on a specific node.
    # [[ref]](https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/#affinity-and-anti-affinity)
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
                - key: feature.node.kubernetes.io/custom-flightaware
                  operator: In
                  values:
                    - "true"

    # resources:
    #   requests:
    #     cpu: 2000m