apiVersion: v1
kind: Secret
metadata:
    name: global-secrets
    namespace: flux-system
stringData:
    INGRESS_DOMAIN: ENC[AES256_GCM,data:BmXVWi2BjR7txb43Rbw8,iv:+Hqav74Er3qSls/aL/rcoZL+eUVsOq/d19cMsp7NFqc=,tag:Jubeko4kQOJoW8qYtKhLnw==,type:str]
    EMAIL_POSTMASTER: ENC[AES256_GCM,data:RVauxfbhQln6VgxcJvKh9sMqzkvnLa5y80wipqf4HvL9Dw==,iv:86YCpk38QX33uWl01qeXK22QE8UCKVHX7sBqGj3Hp+w=,tag:XXzsWPtPekPU3NK3GD8leQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1xsknylevdyrdq858yj57hc0caf477gqyqny8eyl7ekama7ffsf6qrrg28v
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBTUF6Q291N3VJM1V0ZDRR
            dGFJQ0NaM3pIak1CWTAvWXhEVWF4T2tQL0ZnClhpUGh5TG1uSU9nbWlUMFBOdjE0
            d1gvbTRJM2pRa3ZwNmZJenBrZGM2YmcKLS0tIExpRHFVa1lqNHNOL05WY3VnWVdL
            L3FOdDRKRllxMkFlb3Rwd2ZJT2Ywb3cKiZrfSFeBHmkztDOfYqR3I9cnLdW3yYzB
            29Is9EQAhA2vhAC2XkQobqH3lC2pD8JFoj0nryG/zfzG+JXmxq29zA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-04-19T16:25:01Z"
    mac: ENC[AES256_GCM,data:Q7emzaRFeUGllNx1bktSUnFv84smSynxRrk2My+aYBdF+dFmTmoSYaIJoy1m56e8dkNxuo+14KQpzoyJkqf86U6LtC5pC8rnqwbGenos9ci6EnL55zOsXVUerHP/3Xii7MTJV0VQcSec2aVvpqGI4gbgGj54XZ2lH4RPJgAwNho=,iv:hkLXTAQs0qqYSCmeMxIyqnLMjhhcnNJ35OzAJtFSPyY=,tag:mB3+HSHQ0qiB33GkMzKVoA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.2
