---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: influxdb2
  namespace: monitoring
spec:
  interval: 15m
  maxHistory: 2
  timeout: 20m
  chart:
    spec:
      chart: influxdb2
      version: 2.1.0
      sourceRef:
        kind: HelmRepository
        name: influxdata-charts
        namespace: flux-system
      interval: 15m

  values:
    adminUser:
      organization: "influxdata"
      bucket: "default"
      user: "admin"
      retention_policy: "0s"
      ## Leave empty to generate a random password and token.
      ## Or fill any of these values to use fixed values.
      password: "BullFrog"

    persistence:
      enabled: false

    ingress:
      enabled: true
      tls: true
      secretName: tls.influxdb
      hostname: "influxdb.peterduckett.me"
      annotations:
          cert-manager.io/cluster-issuer: letsencrypt
          kubernetes.io/ingress.class: "traefik"

