---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: influxdb2
  namespace: monitoring
spec:
  interval: 15m
  maxHistory: 2
  timeout: 20m
  chart:
    spec:
      chart: influxdb2
      version: 2.1.0
      sourceRef:
        kind: HelmRepository
        name: influxdata-charts
        namespace: flux-system
      interval: 15m

  values:
    persistence:
      enabled: false

    ingress:
      enabled: true
      tls: 
        secretName: tls.influxdb
      hostname: "influxdb.peterduckett.me"
      annotations:
          cert-manager.io/cluster-issuer: letsencrypt
          kubernetes.io/ingress.class: "traefik"

