---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: monitoring-influxdb-pvc-claim
  namespace: monitoring
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 40Gi
  storageClassName: ""
  volumeName: monitoring-influxdb-pv-volume
